version: '3.8'

services:
  gungnir:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
      - ./exports:/app/exports
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gungnir.rule=Host(`gungnir.local`)"
      - "traefik.http.services.gungnir.loadbalancer.server.port=80"

  # Optional: Add a reverse proxy
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
